-- AlterEnum: Add DEMURRAGE_FEE and LATE_PAYMENT_PENALTY to INVOICE_ITEM_TYPE
ALTER TYPE "INVOICE_ITEM_TYPE" ADD VALUE 'DEMURRAGE_FEE';
ALTER TYPE "INVOICE_ITEM_TYPE" ADD VALUE 'LATE_PAYMENT_PENALTY';

-- AlterEnum: Add DEMURRAGE_CHARGED to VAULT_ACTION
ALTER TYPE "VAULT_ACTION" ADD VALUE 'DEMURRAGE_CHARGED';

-- AlterTable: Add currency and demurrage fields to VaultDeposit
ALTER TABLE "VaultDeposit" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "VaultDeposit" ADD COLUMN "demurrageStartDate" TIMESTAMP(3);
ALTER TABLE "VaultDeposit" ADD COLUMN "demurrageRate" DOUBLE PRECISION;
ALTER TABLE "VaultDeposit" ADD COLUMN "totalDemurrage" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable: Add currency field to VaultInvoice
ALTER TABLE "VaultInvoice" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD';
